version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    depends_on:
      - database
    networks:
      - backend

  database:
    image: mariadb:10.6
    environment:
      MYSQL_DATABASE: back_blog
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Run init.sql on startup
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
